return {}
-- return 
--      {
--      'nvimdev/dashboard-nvim',
--      event = 'VimEnter',
--      config = function()
--          require('dashboard').setup {
--              -- config
--          }
--          vim.api.nvim_create_autocmd("FileType", {
--              pattern = "dashboard",
--              callback = function()
--                  vim.opt.foldlevel = 9999
--              end,
--          })
--      end,
--      dependencies = { { 'nvim-tree/nvim-web-devicons' } }
--  }
